admin.home:
   pattern:  /
   defaults: { _controller: CodeMemeAdminBundle:Default:index }

admin.list:
    pattern:  /{slug}
    defaults: { _controller: CodeMemeAdminBundle:Model:list }

admin.new:
    pattern:  /{slug}/new
    defaults: { _controller: CodeMemeAdminBundle:Model:new }

admin.edit:
    pattern:  /{slug}/{id}/edit
    defaults: { _controller: CodeMemeAdminBundle:Model:edit }

admin.remove:
   pattern:  /{slug}/{id}/remove
   defaults: { _controller: CodeMemeAdminBundle:Model:remove }

